### ISSUE TITLE
footer and header not showing up

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#10]
Hi,

I have created a `footer.html` and a `header.html` in _dokuwiki_root_/lib/tpl/readthedokus/.  They read
```
<h1>HEADER</h1>
```
and
```
<i>FOOTER</i>
```
respectively.  However on the page these two elements don't show up, while the content of `pagefooter.html` (reading `<i>PAGEFOOTER</i>`) does:

![readthedokus_no_header_or_footer](https://user-images.githubusercontent.com/279232/134956652-bc859d0c-19fd-45ef-a4bd-ebc2d3052e9d.png)

I must add, that we don't use the template as a general template.  Instead we plan to use it via the [loadskin plugin](https://www.dokuwiki.org/plugin:loadskin) only for one specific namespace.  I.e we can't directly configure the "Template Style Settings" in the Admin panel. But in case the issue is related to these configurations, then there is perhaps a way to configure them otherwise?  I wouldn't mind changing the settings directly in the plugin code, but I don't know where :-)

**Comment by my17560** [comment]
Hi!

As you noticed you need to set header/footer height in "Template Style Settings". You can also change these settings directly by editing a file "(dokuwiki folder)/conf/tpl/readthedokus/style.ini". However if you can't access "Template Style Settings", you might not find the file. Then you need to manually create above file and paste below.

```
[replacements]
__height_header__ = "50px"
__height_footer__ = "50px"
```

These settings should open up header and footer space 50px respectively. Change those heights as you want.

**Comment by fthommen** [comment]
Thanks a lot!
