### ISSUE TITLE
Make use of external fonts configurable

### ISSUE THREAD

**Issue by splitbrain** [my17560/dokuwiki-template-readthedokus#11]
It seems people are struggling with enabling external fonts using meta includes: https://forum.dokuwiki.org/d/19786-struggling-to-include-font-awesome-and-google-fonts-in-template

I'm wondering why it's not simply a setting for the template, so users can enable the fonts with a click?

**Comment by my17560** [comment]
Thank you for letting me know the question in the forum. I'll take care of that question.

I was thinking of adding that feature someday, but I've been lazy and left them untouched. I'll start working on this feature.

**Comment by Cnote43** [comment]
Wow. Thank you both for paying attention to my question in the forum. Your Read the Dokus template combined with Dokuwiki is just pure awesomeness so I'd love to get it working for my team. No pressure or timeline, we're just excited to use it if we can get these external fonts working. I'm not a developer (yet), but I can follow instructions and am happy to test or help out however I can.

**Comment by my17560** [comment]
As I wrote in the forum, putting links in <your dokuwiki directory>/lib/tpl/readthedokus/meta.html should work. My document on the template page was not kind enough since I wrote only file name without a path to it. I'll update it.

**Comment by my17560** [comment]
Though the original issue was solved, I've finished adding the feature and released it.

**Comment by fthommen** [comment]
@my17560 @splitbrain note, that including external fonts w/o proper user consent _could_ be illegal and violate the GDPR if the site is hosted in Europe. See e.g. https://www.linux-magazin.de/news/landgericht-einbindung-von-google-fonts-ist-rechtswidrig/ (sorry, German only)

**Comment by my17560** [comment]
As I wrote in the forum, I will change Google Fonts' location option in settings defaults to blank in the next release.

Thanks for your info.
