### ISSUE TITLE
Question: Recommendation for hierarchically structured documentation?

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#14]
Hi, in our process to convert existing documentation into a format which is suitable for the readthedokus template (like narrower tables, shorter code examples, creation sidebar ecc. ecc.) I have the problem, that our documentation is heavily structured into namespaces (https://our.wi.ki/doc/uber-topic/topic/subtopic/post ecc.). Since the Readthedocs sidebar is flat, the hierarchical structure makes the creation of sidebars complicated. Basically every namespace requires its own sidebar and whenever the structure in a namespace changes, all sidebars have to be manually adapted.

Do you have any recommendations on how to organize the creation and maintenance of such a "farm" of sidebars?

**Comment by my17560** [comment]
I can't say for sure now but maybe I can modify the theme to accept a hierarchical sidebar. Let me try.

**Comment by my17560** [comment]
I updated the theme so that it can show a hierarchical sidebar. Since I haven't updated it officially yet, "Re-install" will update your theme. If this works I'll officially update the theme.

**Comment by fthommen** [comment]
Looks fine even with multiple levels.  Great job && thanks. You can close the issue whenever you see fit
