### ISSUE TITLE
Images are not responsive

### ISSUE THREAD

**Issue by danielhofer** [my17560/dokuwiki-template-readthedokus#17]
Thanks for your great template!
One problem I have: large images has no max-width, so they are much too wide.
Is there a chance to implement a max-width on the img.media class?

Or did I miss a configuration somewhere? Then: sorry:-).

Thanks, Daniel

**Comment by my17560** [comment]
Thanks for your report! I added it to the theme style and released.

**Comment by danielhofer** [comment]
perfect, thanks a lot!
