### ISSUE TITLE
Links have a bigger font size than the titles in the sidebar

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#19]
Hi,

I noticed, that the font size for the titles in the sidebar is slightly bigger than for the page links.  The titles show a computed font size of 13.6px in the Firefox Inspector and the links are 14.1px in size.  Is that by purpose or just a local problem at our site (we have lots of plugins installed :-)?

Cheers, Frank

**Comment by my17560** [comment]
This is by purpose. The styles used are font-size:90% for links and font-size:85% for titles, thus links are slightly bigger. I do this way because the original Read the Docs do this way. I think titles are usually bigger and I don't know why they do this way...

**Comment by fthommen** [comment]
You are right.  I should have compared with Readthedocs beforehand :-). We will probably change this with some custom CSS in `userstyle.css` for our site. Thanks for you swift reaction
