### ISSUE TITLE
Not seeing sidebar

### ISSUE THREAD

**Issue by patdavid** [my17560/dokuwiki-template-readthedokus#2]
I've just installed `2020-07-29 "Hogfather"` and this theme, but no sidebar displays for some reason:

![image](https://user-images.githubusercontent.com/2778928/123837188-2b870c00-d8d0-11eb-8670-bd4dfa2fc514.png)

Is there something silly I'm missing (sorry, not a veteran dokuwiki user so it might be something quite silly).

thx!

**Comment by my17560** [comment]
Hi!

Do you have a sidebar page? Since the TOC is embedded in the sidebar, you need to create one.
Visit http://localhost/sidebar and create it.

This theme's sidebar format is strong for caption, listed links for items.

E.g.
```
** GENERAL **

  * [[[[syntax|Syntax]]
```

Hope this helps.
