### ISSUE TITLE
Utilise full screen width

### ISSUE THREAD

**Issue by Skarlso** [my17560/dokuwiki-template-readthedokus#20]
Hi, 

Wonderful template! :)

Can I ask how I can make it so it uses the full width or at least something wider? 

<img width="1536" alt="Screenshot 2022-02-23 at 13 02 44" src="https://user-images.githubusercontent.com/182850/155315784-913ffbc0-e0dc-499f-b436-ae15b3d97c48.png">

Right now it looks like this, which is super weird. :D A lot of screen estate is unused. And it does this for all pages. So it's not like it expands when there is enough content.

Thanks! :)

**Comment by Skarlso** [comment]
Oh never mind. Content Width 100%. :D

**Comment by rachelgomez161999** [comment]
<div id="full-size">
  Your contents go here
</div>
html,body{ margin:0; padding:0; height:100%; width:100%; }
#full-size{
  height:100%;
  width:100%;
  overflow:hidden; /* or overflow:auto; if you want scrollbars */
}
(html, body can be set to like.. 95%-99% or some such to account for slight inconsistencies in margins, etc.)

**I hope this help ,
Rachel Gomez**
