### ISSUE TITLE
Error 500 :-(

### ISSUE THREAD

**Issue by xroot1337** [my17560/dokuwiki-template-readthedokus#22]
Hello,
Before starting, thanks for this template, it's really usefull and well thought! Congratulation for this work!
While testing the template in a fresh install of dokuwiki (igor), I encountered a problem:
I use a windows 2022 server, IIS and PHP 8.1 : All is ok when i use http://localhost but when I use the FQDN myserver.mydomain.net, I have an error 500. When i reproduce in console mode directly on the server, the following message appears : 

"PHP Waring: Undefined array key "userinfo" in D:\<MyPath>\lib\tpl\readthedokus\tpl_parts\tpl_pagefooter.html on line 17"

Again, when I use http://localhost/doku.php, no problems, i can use the site. When i change the template in configuration manager for argon or dokuwiki, all is ok.
Anyone know how to solve this ?
Thanks!

**Comment by my17560** [comment]
Hi!

As for the warning messages, since some notices are changed to warnings in PHP8 that's the reason.
However, I'm not sure it causes a 500 error.

Anyway, I made a quick fix. Could you re-install the theme and try it?
At least a new one should suppress warning messages.

**Comment by xroot1337** [comment]
Hi!

Awesome, it works 👍 

Fixing as fast as lightning !

Thanks!

**Comment by my17560** [comment]
I'm glad it worked!
