### ISSUE TITLE
template ignores conf/userstyle.css

### ISSUE THREAD

**Issue by tailkinker** [my17560/dokuwiki-template-readthedokus#24]
Exactly as the title states.  Changes to the global conf/userstyle.css are not reflected in the template.  I note the existence of a local userstyle.css, but changes here will likely be wiped out on update.

**Comment by my17560** [comment]
Hi! This theme doesn't handle userstyle.css directly, It is handled by DokuWiki itself.
I've tested conf/userstyle.css myself and it worked fine in my local env.

Some googling showed caching might be the cause. Could you try clearing your browser cache and DokuWiki cache?
Dokuwiki's cache should be cleared by saving the DokuWiki configuration.

**Comment by tailkinker** [comment]
Yeah, that seems to have done the trick.  Thanks, and sorry to bother you with this rookie mistake.
