### ISSUE TITLE
icons not displayed

### ISSUE THREAD

**Issue by twinstef** [my17560/dokuwiki-template-readthedokus#25]
hi,
adminition exclamation & title icon not displayed.

I think the issue is due to a bad installation of "Font Awesome" but there is a lack of explanation about how to do it.

My Readthedokus templates parameters on dokuwiki :
- Enable Font Awesome. => True
- Specify a tag to include Font Awesome ->`<link href='/css/all.css' rel='stylesheet'>`
 
I receive this  string from fortawesome.com -> `<script src="https://use.fontawesome.com/##########.js"></script>`

i then create theses files and put the sring inside:
- /conf/meta.html
- /lib/tpl/readthedokus/meta.html

Without any succes.

Could you explain how to deal with this template to have icons displayed ?

Regards,
Stéphane.

![image](https://user-images.githubusercontent.com/18529292/208066050-af3d0dbd-cc04-402e-880f-4b3809c1800f.png)
![image](https://user-images.githubusercontent.com/18529292/208066169-28c1d1e4-ba54-47cb-aaa2-ddc0d6dc48e3.png)

**Comment by my17560** [comment]
Hi, thank you for using the ReadtheDokus template, and sorry for lacking information.

Could you try putting the string from fontawesome.com into the "Specify a tag to include Font Awesome..." option?

i.e.
Specify a tag to include Font Awesome...: <script src="https://use.fontawesome.com/##########.js"></script>

If it does not work, could you try simple HTML without DokuWiki, creating index.html like this:

<html>
<head>
<script src="https://use.fontawesome.com/##########.js"></script>
</head>
<body>
<i class="fa-solid fa-house"></i>
</body>
</html>

If the home icon doesn't appear then the path is wrong. If it shows the correct icon then .... tell me and I'll find out other solutions.

**Comment by twinstef** [comment]
thank's for your reply.

So i tried as you suggested with a simple index.html.
results:
  - <i class="fa-solid fa-house"></i> => No Icon At All
  - <i class="fa-solid fa-home"></i> => Bad Icon  ![image](https://user-images.githubusercontent.com/18529292/208154699-5a93d2fd-cbd7-4847-81d9-b686a8e08238.png)
  -  <i class="fa fa-solid fa-home"> => Good Icon  ![image](https://user-images.githubusercontent.com/18529292/208154924-97a57525-9cd7-4b20-82a2-b787dd2a3a9d.png)

So i do not understand if something changed in the syntax of fontawesome or if i have only a lite acces ...
But on the web site https://bitsmist.com wich use the same template the icons are good - but this site can also use a local icon library.

Regards,
Stéphane Comparetti

**Comment by twinstef** [comment]
It looks like the last version of font awesome that i can use for free is the 4.7 and doesn't include icons from this template.
for example fa-house is in the version 6 and not in the 4.7

**Comment by twinstef** [comment]
I made a new inscription on https://fontawesome.com and now i have acces to the version 6.2 and etherything works fine !
(I first made by mistake a registration on the CDN version of fontawesome which seems to be limited to version 4.7)
