### ISSUE TITLE
Wrong resizing to <img> and <svg>

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#28]
Hello,
I started using Read the Dokus at my Wiki but noticed that big images ``<img />`` tags can overlap the text area:

![image](https://user-images.githubusercontent.com/2974895/216036126-4c914488-5af9-4d9b-899d-a8a441072620.png)

Also noticed that SVG images are small. I believe it may happening because there should be a generic ``svg`` resize tag somewhere (e.g. to resize Font Awesome icons), but I'm not sure.

![image](https://user-images.githubusercontent.com/2974895/216036313-17974f6b-9f7f-4f03-944e-cd83c04aedee.png)

I believe that commiting some CSS code like this may fix the issue:

```
#dokuwiki__content img, #dokuwiki__content svg {
    max-width: 100% !important;
    height: 100% !important;
}
```

**Comment by my17560** [comment]
I'll add max-width:100% to image and svg. However setting height:100% to all images/svg might cause backward compatibility issues so could you put height:100% to your own style?

I think svg is small because it is styled in lib/styles/all.css.

svg {
    width: auto;
    height: 1.2em;
}

**Comment by eduardomozart** [comment]
> I'll add max-width:100% to image and svg. However setting height:100% to all images/svg might cause backward compatibility issues so could you put height:100% to your own style?
> 
> I think svg is small because it is styled in lib/styles/all.css.
> 
> ```
> svg {
>     width: auto;
>     height: 1.2em;
> }
> ```

Hello @my17560,
I've applied your last Master version of the template from GitHub repository and I can confirm that ``<img>`` with larger sizes are being rendered as expected, but ``<svg>`` images are still small. I believe that this SVG code should be changed to a more specific one to avoid it changing ``<svg>`` image sizes. If not possible, the https://github.com/my17560/dokuwiki-template-readthedokus/commit/63803b35f32e3345f15b95d2e72f122a59a3108b commit should be changed to apply an "height: auto" (default) for SVG images.

**Comment by my17560** [comment]
Adding height:auto sounds reasonable. I'll add it to the style.

**Comment by eduardomozart** [comment]
Hello,
I can confirm that your last commits to the repo fix the rendering of SVG and IMG tags. Thank you!

**Comment by eduardomozart** [comment]
I noticed that some SVG still overlaps. not sure if there's anything we could do to avoid it from happening.
![image](https://user-images.githubusercontent.com/2974895/216586567-d2bb9bab-978c-4ef7-be63-fcdb7fbbb08c.png)

**Comment by my17560** [comment]
I can't reproduce the situation so if you could give me the svg file that causes the problem, I might be able to investigate.

**Comment by eduardomozart** [comment]
I was able to confirm that indeed I could not also reproduce the issue anymore, I believe I was using a CSS cached. Now the SVG adjusts to the page as expected.

**Comment by eduardomozart** [comment]
But I noticed that when using emojis like ``:!:`` and ``;-)`` they render as SVG and are not small. Not sure if it's related to the commit made by this issue.
![image](https://user-images.githubusercontent.com/2974895/216827210-90ef7fac-8504-4d32-ad91-f7a5b8324891.png)

**Comment by my17560** [comment]
Yeah, surely that's because of the commit I made...
I've fixed it to apply "height:auto;" only to svg. Please give it a try.

**Comment by eduardomozart** [comment]
I can confirm with your last commit that the images and SVG are being rendered as expected. Thank you!

**Comment by eduardomozart** [comment]
> I noticed that some SVG still overlaps. not sure if there's anything we could do to avoid it from happening. ![image](https://user-images.githubusercontent.com/2974895/216586567-d2bb9bab-978c-4ef7-be63-fcdb7fbbb08c.png)

Hello,
I'm not sure what happened, but this image is still overlapping available space. It's available at https://www.plantuml.com/plantuml/svg/lLLHRzem47xFht3JFI51I61QMtMeBTNwGgjgCFQmJfMR7C72iQEpKxPL_U-pdOII0PFMiHc9IBxxlllY-yxnpfIcg8kCUnncccX9aALpJHA646icXUUf1HCvHPgH9u-OTOuebqF99P8BJkE5sxo46Isudi0tVSvPAZ8GciJc3z35RwI6Pj3MSw7nd2PooKHAPfGhy9xNIreLLAGSgk8Nfc2AiX19gK0Z5Sga6iOoBZ41t8mrI8KHK_Ev_CcSnGi1If5mQvN3cLljmrbaVoxdWnIwYdRTiZKE4fWn0MJwSN9h3fNCjSxLIH0WNNPIfkV5Gw40OmCreZgnp0982eg9pEGFquV0uDgtd0hzwNeKP5IPumiIfhHtm4JCYsJ570mvCnJA8aOqrpBlvBQB6tate9SIpQkdDdMyP3gUxqXjK1gPjyXi_tPaJvagA6UAMfTOp70ucTuFQGP8Tq36W8-0hi14BW7louqostjfjNyQsuCzIMII0Zxm0WQjrdHqVaDwhTPfu8A3Et4dJj-iNlz9nPJ3-swd7puFV48LAVV3l-1zEOCLU-zTnLu5jj5pba6A0A9cx_-nwcYRQeeBfzdXoqwky6yDlgxXUCQVGy_v_45gBJDZMQENf67G3KgFcvLBD7F8nAAjl-T0Q1oR4MW4ootoQ2n9UkiSqUiu-kiSlNtewDTvrIaX98DV-3GMOb4VpgvqbqHom8pfgawxlmA1IDojyQzSsdkjZTQ6hk45nss3hpRe-eHkoYxtmptODDfbqwCzMEnu3nOBz-7r_-xJwlOZtVQNmqldq0lJbA_cIolQNU9VkJSZlhqdo8bvbiltwdljjy3U5c1rSJdSo1ZioXfi1RiJ3XXjuZoxuPCotFSDlb4gwhjQaSsBwhnZVuUyQfeQ1TPmOUHlr-ScPHDLgJxQWQg6e84xCosmdxEV

To download it, right click on link and select "Save link as" and save it with ``.svg`` extension.

**Comment by my17560** [comment]
I downloaded the file and tested it on my env and it appears as expected, fit in screen width. Does CSS apply to your image tag?

```
#dokuwiki__content img,
#dokuwiki__content svg {
    max-width: 100%;
}
```

I embedded the SVG using Media Manager like this
```
{{ :test.svg |}}
```

**Comment by eduardomozart** [comment]
It seems that PlantUML Parser plug-in is setting width and height manually at the ``svg`` tag so it's overriding those templates CSS values. This issue doesn't seem to be related to this template, so I'll close it. Someday I will update PlantUML Parser for it to be able to set width on the plugin tag itself. Thank you!
