### ISSUE TITLE
"/home/robertinho/public_html/wiki/inc/template.php on line 1805 dokuwiki mode_ tpl_readthedokus loggedIn notFound"

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#29]
Hello,
I started using the Read the Dokus template. I'm running PHP 8.1 with the latest stable release (DokuWiki "Igor") and I'm receiving the following error message at the top of the popup page when opening the Media Uploader while editing a page:

````
/home/robertinho/public_html/wiki/inc/template.php on line 1805
dokuwiki mode_ tpl_readthedokus loggedIn notFound ">
````

![image](https://user-images.githubusercontent.com/2974895/216037494-b977ae57-6895-46ed-9044-dabd7b807ff3.png)

**Comment by my17560** [comment]
I confirmed the warning messages. Seems like some messages were trimmed on your screen. Actually, I got this message.

```
Warning: Undefined variable $fullscreen in /Users/masaki/Projects/bitsmist.com/public/lib/exe/mediamanager.php on line 124
/Users/masaki/Projects/bitsmist.com/public/inc/template.php on line 1805
```

There are two warnings and both of them come from Dokuwiki itself, not the template. So the author of Dokuwiki is responsible for these.

The quick fix below suppress the warnings, but I'm not sure if it's correct.

lib/exe/mediamanager.php line 13-17

    global $INPUT;
    global $lang;
    global $conf;
+    global $fullscreen;
    // handle passed message


int/template.php fix line 1805

-        (isset($INFO) && $INFO['exists']) ? '' : 'notFound',
+        (isset($INFO['exists']) && $INFO['exists']) ? '' : 'notFound',

**Comment by eduardomozart** [comment]
Hello,
Not sure what happened, maybe was your lasts Master commits (as I applied them at my Read the Dokus template), but the error seems to be fixed without applying your patches at my DokuWiki instance (as they didn't seem to be applied at the last DokuWiki source code commit right now). I only applied the https://github.com/splitbrain/dokuwiki/pull/3739 fix at my DokuWiki, but it didn't seem to be related to this issue.
