### ISSUE TITLE
No css style for "Select a file" button from Media Uploader

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#30]
Hello,
Not exactly a bug, but I noticed that the "Select a file" from Media Uploader popup has no CSS applied into it. I believe that a CSS like a button would be great, as it's the default behavior in other templates.
![image](https://user-images.githubusercontent.com/2974895/216037494-b977ae57-6895-46ed-9044-dabd7b807ff3.png)

**Comment by my17560** [comment]
I didn't realize the select file button is not styled at all...
I'll add styles to looks like a button.

**Comment by eduardomozart** [comment]
I've applied your last Master commit into my Wiki instance and I can confirm that the "Select a file" has a button style applied into it. Thank you!
