### ISSUE TITLE
Add CSS support for the AcMenu as sidebar

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#32]
Hello, I’ve seen in past closed issues that you recommended the simpleNavi plugin to the sidebar, but I noticed that it has a static sidebar instead of a collapse one so I decided to use the AcMenu as sidebar because it offers a collapsable sidebar and it works as expected. It has some bugs rendering the title but I’ve already reported it at https://github.com/tormec/AcMenu/issues/10. It would be great if the CSS from simpleNavi plugin as sidebar also applies at the AcMenu one.
![6C0833B3-A25D-40CD-8C41-8FB1C789E926](https://user-images.githubusercontent.com/2974895/216201547-81ec5237-7b32-48c6-ae0e-4423ac0390c2.jpeg)

**Comment by my17560** [comment]
I've never used the AcMenu plugin before, so I'll test it and check if I can apply the style.

**Comment by eduardomozart** [comment]
Hello @my17560,
Thank you for helping me to set me up your template and make it better for everyone.
I would like to thank you somehow so I decided to work into AcMenu integration with your template, this is how it is:
![Animação](https://user-images.githubusercontent.com/2974895/216570828-f44a4d18-3b7a-4178-bf56-6807c0c4c929.gif)
I'll send a PR to your repo so you could add the compatibility to AcMenu as a sidebar. But notice that to work like the video above it require code changes that I'll PR to the AcMenu repo, but I'm not sure if the plug-in owner will accept them because they are bigger one. But if you are interested I can fork the AcMenu and/or you can provide it with your template.
