### ISSUE TITLE
Alignment between text-fields into Login form

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#33]
Hello,
Not a big issue at all, but I believe it would offer a better user experience if the "Username" and "Password" fields from Login form align it's text and label fields. The position below is just a suggestion.
![image](https://user-images.githubusercontent.com/2974895/216307316-4dc74bce-690b-4ede-85f3-1e6f33203a9b.png)

**Comment by my17560** [comment]
This is because of my last modification that changed the alignment to center. I'll revert the alignment to right.

**Comment by eduardomozart** [comment]
Hello,
I can confirm that your last commits to the repo fixed the login form alignment. Thank you!
