### ISSUE TITLE
Option to change img/svg border at Style Configuration

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#34]
Hello,
It would be great if an option to customize the ``<img>`` and ``<svg>`` color borders would be available at the Style Configuration. It could come as "transparent" (none) by default as today and an option to change it available at the Style Configuration. There's an example below of images with and without borders.
![image](https://user-images.githubusercontent.com/2974895/216308623-1965d31d-00a1-458e-9a01-80f417b22010.png)
Thank you for developing this beautiful template!

**Comment by my17560** [comment]
Sorry but I can't add the option since I can't set "transparent" as default in that option screen with the color picker.

Please put your styles into conf/userstyle.css.
