### ISSUE TITLE
Line Break between "Visited" and "You are here" into Breadcrumb

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#35]
The default behavior from DokuWiki default template and Argon is to show "Visited" and "You are here" into different lines, but the template show them at the same line when Breadcrumb is enabled at the template config, as can be seen below:
![image](https://user-images.githubusercontent.com/2974895/216320698-2b5aa73b-20f3-4252-9ba0-92ea34b4518a.png)

**Comment by my17560** [comment]
I'll fix it to look like the original.

**Comment by eduardomozart** [comment]
I can confirm that your last commit renders the Breadcrumb similar as the default template and other ones. Thank you!
