### ISSUE TITLE
Add Anchor (Font-Awesome) icon on Headers hover

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#37]
It would be great if hovering a title it shows a hiperlink to refer it's specific page section for users with Font-Awesome enabled at the config, as GitHub does for README files:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/2974895/216420652-eca627be-b899-4058-811a-2d18a0643ccf.png">

**Comment by my17560** [comment]
Sorry but I don't have a plan to add that feature since sidebar toc shows the same list.

**Comment by eduardomozart** [comment]
I see. No problem. I know that there's a link for the TOC at the Sidebar, but I believe that adding them at the title would be a small and useful feature too.
