### ISSUE TITLE
Larger tables is overlapping text area

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#38]
Hello,
I noticed that larger tables are also overlapping the text area, similar to PNG before your patches.
![image](https://user-images.githubusercontent.com/2974895/216568834-9e6d8716-1e64-4237-a259-3dc9f2269e6b.png)
Thank you for investing your time to improve this template! It's amazing!

**Comment by eduardomozart** [comment]
Not sure if related to this bug, but when trying to view a table in rotate mode at iPhone XR it’s not possible to see all horizontal page content. I believe it’s related to overflow. It should be possible to touch the screen and see remaining columns from larger tables.
![B091E4DC-61EE-45A9-A90E-D24DFA0C8323](https://user-images.githubusercontent.com/2974895/216841272-443db81b-0ce7-4313-9e39-c6446d92dd21.png)

**Comment by my17560** [comment]
I've fixed it to show scroll bar when table size exceeds the content width

**Comment by eduardomozart** [comment]
Hello,
Thank you! I can confirm that on iOS and computer the table overflows so it's rendered inside the textarea and I can see it's content scrolling horizontally as expected.
