### ISSUE TITLE
How to add a sticky header and "Back to Top" button?

### ISSUE THREAD

**Issue by yysquare** [my17560/dokuwiki-template-readthedokus#4]
I like what showed in https://bitsmist.com/

but it seems the sticky header and B2T button are not supported by default.

So I would like to know how to add them just like what it looks like on https://bitsmist.com/. Because I want to use this theme for my language learning DokuWiki, so it contains a lot of long pages. A sticky header and B2T button will be very useful on mobile devices.

Thanks!

**Comment by my17560** [comment]
Hi! To add a sticky header, visit the "Template Style Settings" page from the Administration page. You need to log in. On the page, edit "Header height" to set your header height. e.g. "50px".

Then, create a file "header.html" under (dokuwiki folder)/lib/tbl/readthedokus/

Here is a sample header.html. This example also shows how to toggle a sidebar. Clicking the string "Header" toggles the sidebar.

```
<div onclick="toggleMenu();">Header</div>
<style>
header > div {
	background-color: khaki;
	position: fixed;
	height: 50px;
	left: 0;
	top: 0;
	right: 0;
}
</style>
<script>
function toggleMenu()
{
	dokus.toggleSidebar();
}
</script>
```
You might want to hide a mobile menu since both the sticky header and the mobile menu are displayed at the same time on mobile devices. To hide the mobile menu add below to CSS file (dokuwiki folder)/conf/userall.css

#mobileheader {
	display: none;
}

**Comment by my17560** [comment]
To add a back to the top button I use my own framework "BitsmistJS". If you don't want to use the framework the following page might be helpful.

https://www.w3schools.com/howto/howto_js_scroll_to_top.asp

Put HTML in (dokuwiki folder)/lib/tbl/readthedokus/tpl/util.html, CSS in (dokuwiki folder)/conf/userall.css, and Javascript in (dokuwiki folder)/conf/userscript.js.

If you don't mind using the framework, here is an instruction:

1. Include the framework.

Create (dokuwiki folder)/lib/tpl/readthedokus/meta.html and paste below inside the file.

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/bitsmist/bitsmist-js_v1@0.9.11/dist/bitsmist-js_v1.min.js"></script>
```

2. Upload back to the top component files attached.

[Archive.zip](https://github.com/my17560/dokuwiki-template-readthedokus/files/7095730/Archive.zip)

You need to unzip the file. There are 2 files inside the zip file and upload them to your site. 

3. Add the back to the top button in util.html

Create (dokuwiki folder)/lib/tpl/readthedokus/util.html and paste below inside the file.

```
<button-totop bm-autoload bm-path="/"></button-totop>
```

Please be noticed bm-path="/" specifies the path to the back to the top button component you uploaded. This example assumes you uploaded it to the root folder.

Hope this helps!

**Comment by yysquare** [comment]
@yysquare I have followed your guidance and everything looks good now. Thanks again!!

btw. 

> Put HTML in (dokuwiki folder)/lib/tbl/readthedokus/tpl/util.html, CSS in (dokuwiki folder)/conf/userall.css, and Javascript in (dokuwiki folder)/conf/userscript.js.

the path you mentioned should be: (dokuwiki folder)/lib/tpl/readthedokus/util.html

**Comment by my17560** [comment]
I'm glad it worked!

And thank you for correcting the wrong path.
