### ISSUE TITLE
Overflow sidebar items to the right instead of moving it to the left

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#41]
Hello,
I noticed that when sidebar items are long the sidebar moves the ">" icon to expand the sidebar to the left, making it difficult to click into the button. I believe that the content from sidebar should be overflowed instead of moving the content.
![image](https://user-images.githubusercontent.com/2974895/216612209-c4160f3f-1979-41be-969f-d24f180bce58.png)
The top right of the sidebar also seems to be moving.
![image](https://user-images.githubusercontent.com/2974895/216616291-49aeb2b0-c552-4853-a8d8-a95f0f871cfc.png)

**Comment by my17560** [comment]
I found a bug regarding sidebar width and I've fixed it. However I'm not sure if the fix solves this problem. Could you try the latest?

**Comment by eduardomozart** [comment]
This seems to be fixed at the latest commit. Thank you!
