### ISSUE TITLE
No LogIn button once LogOut

### ISSUE THREAD

**Issue by tormec** [my17560/dokuwiki-template-readthedokus#43]
I'm testing the very last version of this template (06/02/2023) and once I log out I don't see any link to log in again (see screenshot).
I have to manually restore the dokuwiki template in `dokuwiki/conf/local.php` to be able to log in.
![image](https://user-images.githubusercontent.com/10964663/216989894-f4c432a3-8677-458a-ba15-d5e88a3f1ca6.png)

**Comment by tormec** [comment]
My fault, I didn't see the option
`tpl»readthedokus»showtoolboxalways_enable`
but what is its purpose?
Because if one (accidentally) logs out and that option is not validated, then one cannot log in again "easily".

**Comment by my17560** [comment]
I created the template to show software documents and wanted a site to look like a normal web site, not a wiki site. That's why I hid the login link and other menu.
