### ISSUE TITLE
Hide Title if user has no access to it

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#45]
Hello,
After LogOut, the user are still able to see the path of the page he/she is trying to access at the Breadcrumb and the Title of the page. Not exactly a bug, and I know it's the default behavior of DokuWiki (as far as I've seen into other templates too), but I believe it should be great to hide the Title of page if user isn't authenticated and isn't logged in into DokuWiki while trying to access a namespace he/she has no access to. Not sure if it's possible though.
<img width="1281" alt="SCR-20230206-x5t" src="https://user-images.githubusercontent.com/2974895/217492141-a248bc9a-d483-45ad-899b-7a12797e3cfb.png">

**Comment by my17560** [comment]
Sorry but the feature you are asking for is beyond the scope of this template. You should ask to the Dokuwiki author.

However, you can hide breadcrumbs when you are logged out with css. When you are logged in, div#dokuwiki__site has loggedIn class. so adding the style below will hide breadcrumbs when you are logged out.

#dokuwiki__site:not(.loggedIn) .breadcrumbs
{
	display: none;
}

**Comment by eduardomozart** [comment]
Thank you!
