### ISSUE TITLE
Wrap plugin style isn’t shown inside a list

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#47]
It was working as expected into Argon Alt template but isn’t with Read The DOKUS template.
![5E60C765-8605-4E2A-A087-03B8A6ED67F1](https://user-images.githubusercontent.com/2974895/217515009-53a63289-e9be-4367-9efa-aa36b887fbc5.png)
![455C99D4-96CD-447D-91B2-2EEF59D68EC2](https://user-images.githubusercontent.com/2974895/217515031-18957959-f4e6-4dec-8d58-98fc41342a79.png)

**Comment by my17560** [comment]
Did you put "admonition,danger,caution,note,tip" to wrap plugin's "noPrefix" option as my document says? If so remove them and it would work fine. Wrap plugin uses "wrap_tip" class so you can't put "tip" into that option.

This means if you want to use both wrap plugin tip and readthedokus admonition, you can't use wrap plugin for readthedokus admonition.

**Comment by eduardomozart** [comment]
Oh, I did. Strange is that it's there but Wrap still works outside of the lists as expected. Not sure what's going on. Anyway, I'll use BatchEdit to change all wrap styles for the template style. Thank you!
