### ISSUE TITLE
Add support for Ctrl + Enter

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#48]
Hello,
I know that the official Read the Docs template didn't offer this feature, but I use it a lot. Sometimes I'm reading a page and I would like to search a term at my Wiki. But doing so I'm forced to exit the page to load the search results. It would be great if I press Ctrl+Enter or Command+Enter it opens the search page in a new tab, or if there was a search icon to right click and select "Open in a new tab".
Maybe if Font Awesome is enabled into the template it could add a search icon inside at the right of the search bar (and left on RTL languages).

**Comment by my17560** [comment]
I'm not planning to add the feature to this template, but that's possible by javascript code. Put the following code to conf/userscript.js and it will do (ctrl+enter). I've only tested on chrome on mac.

```
(function () {
	let searchBox = document.querySelector("#dw__search");
	if (searchBox) {
		let openTab = false;
		searchBox.addEventListener("keypress", function(e){
			if (e.code.toLowerCase() === "enter" && e.ctrlKey === true) {
				openTab = true;
			}
		});
		searchBox.addEventListener("submit", function(e){
			if (openTab) {
				event.stopPropagation();
				event.preventDefault();
				openTab = false;
				window.open(window.location.href + "&do=search&q=" + document.querySelector("#qsearch__in").value);
			}
		});
	}
})();
```

**Comment by eduardomozart** [comment]
Hello,
I can confirm that it works as expected, but it should be added inside a ``jQuery(document).ready(function() { });`` block, otherwise it didn't work. Thank you!

**Comment by eduardomozart** [comment]
I had to edit it a little bit to make it work on Windows. Your code was setting the variable "opentab" to "True" on Windows but I had to press Enter again so it opened a new tab. To have the desired effect on a Windows machine, I had to change "keypress" to "keydown" and trigger the "submit" event manually:

```
  (function () {
	let searchBox = document.querySelector("#dw__search");
	if (searchBox) {
		let openTab = false;
		searchBox.addEventListener("keydown", function(e){
			if (e.code.toLowerCase() === "enter" && e.ctrlKey === true) {
				openTab = true;
				searchBox.dispatchEvent(new Event('submit'));
			}
		});
		searchBox.addEventListener("submit", function(e){
			if (openTab) {
				event.stopPropagation();
				event.preventDefault();
				openTab = false;
				window.open(window.location.href + "&do=search&q=" + document.querySelector("#qsearch__in").value);
			}
		});
	}
  })();
```
