### ISSUE TITLE
Clear Float on "Mass Import" on User Manager

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#50]
The section "Mass Import" from User Manager seems misaligned. I'm not sure, but I believe a CSS ``clear: float`` may fix the issue.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/2974895/218556613-fb149c37-a911-49f1-b54f-d56bc357aebc.png">
The same section with the default DokuWiki template:
<img width="970" alt="image" src="https://user-images.githubusercontent.com/2974895/218556470-cb6ca08c-0040-42f1-849e-bbfc18f28ffb.png">

**Comment by my17560** [comment]
I can't reproduce the issue. The section looks as expected on my machine.

**Comment by eduardomozart** [comment]
Oh, I see. I forgot to say: To the problem to happen, please click into a user into the list with the intention to edit it. You will see that it will break the Mass Import page layout.

**Comment by my17560** [comment]
Thanks, now I could reproduce the issue. I fixed it.

**Comment by eduardomozart** [comment]
Hello,
I'd applied your last commit and now the User Manager seems to be working as expected. Thank you!
