### ISSUE TITLE
"Page footer text color" shows as text instead of color input on Manage User Style

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#51]
Hello,
When customizing the template colors, the "Page footer text color" shows as text instead of selecting a color using Color Picker:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/2974895/218578549-104f2c4c-2ea7-406c-9613-77b2c37ff7f9.png">

**Comment by my17560** [comment]
Thanks. My stupid mistake. I fixed it.

**Comment by eduardomozart** [comment]
Hello,
I can confirm your latest commit fixes the issue.
