### ISSUE TITLE
Increase readability of strong font-size color

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#53]
Hello,
I would like to suggest the following CSS change to the template:
````
strong {
   text-shadow: 0 0 0 __text__;
}
````
Because it's difficult to differ bold text from non-bold text.
Before:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/2974895/218580418-17e7332e-d5d3-40b0-9537-7d14d871974c.png">
After:
![image](https://user-images.githubusercontent.com/2974895/218580465-da00d7cd-344a-46a7-a51e-20c4ab096179.png)

**Comment by my17560** [comment]
Thank you for your suggestion.

But it could depend on the fonts you are using and adding text-shadow makes some fonts too bold and blurred. I want to leave that to each user whether to make it bolder or not. So please put the style in userall.css.

**Comment by eduardomozart** [comment]
I understand. I noticed that the bold seems to render as expected on Windows, it just doesn't seem right on macOS. I'd applied the change manually at the ``conf/userstyle.less`` file. Thank you!
