### ISSUE TITLE
No "subscript" support

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#54]
Hello,
I'd noticed that on [DokuWiki Syntax](https://www.dokuwiki.org/wiki:syntax) page there's an option to use subscript text with ``<sub>subscript</sub>`` tag, but it didn't seems to work with Read the Dokus template.

**Comment by my17560** [comment]
Thanks. This is the same reason as #36. I added the styles.

**Comment by eduardomozart** [comment]
Thank you! I can confirm it's working as expected now.
