### ISSUE TITLE
"Edit this page" edit the current page instead of page revision

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#55]
Hello,
When using the Revision plugin to browse an old revision of the page, clicking into the "Edit this page" at the top right of the page, it edits the current page revision instead of the old revision I'm browsing. The only way to edit the old revision is using the "Edit this page" link available at the "Page Tools" at the bottom.

**Comment by my17560** [comment]
Which plugin? "[revisionat Plugin](https://www.dokuwiki.org/plugin:revisionat)"?

**Comment by eduardomozart** [comment]
No, it is the built-in Revision Manager - https://www.dokuwiki.org/plugin:revert

**Comment by my17560** [comment]
Thanks. I wasn't aware since I've never edited old revisions before. I've fixed it.

**Comment by eduardomozart** [comment]
I can confirm your last commit fixes the issue. Thank you!
