### ISSUE TITLE
Page TOC isn't shown on Revision page

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#60]
Hello,
When accessing an old revision of the page and not using the ``navigation`` plugin, the Page TOC isn't loaded, so we can't easily browse through titles on old revision pages.

Actual Page:

![image](https://user-images.githubusercontent.com/2974895/223138549-eb6f8ec9-c18e-4a8b-a566-a9a2a2ce5680.png)

Revision Page:

![image](https://user-images.githubusercontent.com/2974895/223138245-a943fdba-a428-48e7-a9c3-261ced994f40.png)

**Comment by my17560** [comment]
I've fixed it. Try re-installing the theme.

**Comment by eduardomozart** [comment]
Hello.
I can confirm it's working as expected on Revision pages with your last commit. Thank you!
