### ISSUE TITLE
Rotating the screen sidebar keep left space

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#62]
Not sure if it’s a bug or intended, but when rotating my phone it seems that the left sidebar has a space on the left side. 
![AFC47550-9C82-42F9-8D06-F0B1E061483A](https://user-images.githubusercontent.com/2974895/225924065-5f0ffe7b-63e7-434c-a7ed-d58785df5819.png)
The page also didn’t seem to fit the full page (I believe it is because I set 70% for page content width as can be seen in #61 and when rotate its larger than 768px, so it’s fine if expected).

**Comment by my17560** [comment]
I'm trying to re-produces the issue but I can't. I don't have an iPhone so I've tested with my android phone. I'll keep investigating it.

What I've realized is that there is a blank not only on the left of the content but also on the left of the back button on top of the screen. Maybe Safari's bug?

If your phone is larger than 768px on a horizontal screen and you set the width to 70%, it is expected to not fit a full page.

**Comment by eduardomozart** [comment]
I see. I’m using Google Chrome on iOS. I didn’t tried, but Google Chrome (Desktop) has an option to simulate an iPhone device. If we can’t reproduce the “issue” there, I believe it didn’t worth the effort to troubleshoot this, as it didn’t affect the usability at all. Maybe even a browser feature, because the back button of the browser is aligned to the sidebar as you stated.

**Comment by my17560** [comment]
Some googling tells me there are "Safe Areas" in iOS browsers. This might be the cause of this issue. I've added an option to the viewport meta settings to remove the safe areas. Could you try?

**Comment by eduardomozart** [comment]
Hello,
It didn't seem to fix the issue, but I believe that space exists because iPhone has a notch and that same space is reserved in another websites, like Google Web search, so I believe it's intended and not a issue at all.
