### ISSUE TITLE
Replace draft recover white background with theme color

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#63]
Hello,
When recovering a draft, the background is white. It could follow the color of the background of the page.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2974895/227555559-af74d264-c9d8-470f-9d06-ec52ba33e139.png">

**Comment by my17560** [comment]
Thanks. I've never realized this with my monitor, since they all look the same white. I've fixed it and committed to Github.

**Comment by eduardomozart** [comment]
Thanks, I can confirm your last commits fixes the issue.
