### ISSUE TITLE
Login button/link

### ISSUE THREAD

**Issue by nixfu** [my17560/dokuwiki-template-readthedokus#65]
I love this template, but it would be nice to be able to have the default login functionality back to provide a login link/button, when the user is not logged in.  I added a login link to our sidebar but it looks kinda janky.

**Comment by my17560** [comment]
There is an option "Show toolbox even when logged out" in "Configuration Manager" - "template" - "Readthedokus". Please check it; then the Tool Box menu appears under each page even when logged out. There is the "Login" link in the menu.

**Comment by tormec** [comment]
Perhaps,  if the option
https://github.com/my17560/dokuwiki-template-readthedokus/blob/3b961a9c718a0b6261efe222a602566a121ce574/conf/default.php#L4
was `true` by default, it would cause less confusion.

**Comment by my17560** [comment]
Sorry for the confusion. I wanted to make it look like a regular web page, not a wiki page when logged out.

**Comment by my17560** [comment]
It’s been a while since the last comment, I’m closing the issue. If you still have any problems, please reopen this issue or create a new one.
