### ISSUE TITLE
Misaligned refresh icon on SearchIndex Manager plugin

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#67]
Hello,
The progress icon of [SearchIndex Manager plugin](https://www.dokuwiki.org/plugin:searchindex) when rebuilding the index seems misaligned on Read the Dokus template. The text doesn't overlap the icon on DokuWiki default template.

<img width="876" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/101d6a79-0630-4aa4-8504-33762556d5d4">

**Comment by my17560** [comment]
I've added the CSS for the plugin. Could you re-install the theme and try it?

**Comment by eduardomozart** [comment]
I can confirm it's working as expected. Thank you!
