### ISSUE TITLE
Question: How to create a readthedocs-style sidebar?

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#7]
Hi,

I tried but did not succeed in creating a sidebar with the readthedocs style, i.e. where the currently selected page is highlighted and with (un)foldable chapters as you show on https://bitsmist.com/en/bitsmistjs/docs/general/overview?

Can you give short hint, how that can be achieved?

**Comment by my17560** [comment]
HI!

At first, you need to create a sidebar page. You can create it by making a page called "sidebar".

Example:
```
** GENERAL **

  * [[test1|TEST1]]
  * [[test2|TEST2]]
```

Next, this theme uses a table of contents(TOC) to show folderble menu on the sidebar. So make sure the page has a TOC.

https://www.dokuwiki.org/toc

Example: Make a page called "test1" and paste below.
```
====== TEST1 ======

===== TEST1-1 =====

===== TEST1-2 =====
```

An above example should show a sidebar and a TOC inside.

![Screen Shot 2021-09-21 at 11 00 39](https://user-images.githubusercontent.com/49435291/134100823-5fd79b3e-a5a1-4c61-b8d5-425909a1dd1a.png)

The theme searches inside the sidebar that has the same address as the current page. If found the TOC will be embedded there, If not found it will be displayed under "Table of Contents"  section in the sidebar.

**Comment by fthommen** [comment]
Thanks a lot.  That helped me understand how this works.  However I have several DW instances.  In most of them this works fine, but in one the sidebar does link to the respective page, but doesn't show the pages' TOCs and the highlighting.  I suspect that some Plugin might be the culprit.  However this is a productive Wiki with lots of installed plugins and my possibility to do "live experients" is somewhat limited.  Do you have an idea how I could try to debug this issue?

**Comment by fthommen** [comment]
Found the issue and posted as #8
