### ISSUE TITLE
Non-full width on mobile phones

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#70]
Hello,
I believe this "issue" is related to #68, when the login screen for unauthenticated users was changed to 80%, but I believe that smartphones should still use 100%.
<img width="414" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/67928601-70c9-4534-92be-cf83c8cc81ec">
When typing a wrong username/password combination it shows up 100% width as expected:
<img width="414" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/7796636b-7ea7-4cef-9adc-169f39711ce5">
Here is my current template style settings:
<img width="876" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/597582e8-cb0f-4d20-9c2c-1f649b702f85">

**Comment by my17560** [comment]
Hi, thank you for your report. I've fixed it. Could you re-install and try it?

**Comment by eduardomozart** [comment]
Hello, I can confirm this fixed the issue. Thank you!
