### ISSUE TITLE
"Additional plugins" section doesn't seem right

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#71]
Hello
I believe that "Additional plugins" (Plugins adicionais) is misplaced, maybe it should be below with the items below it, in both of my wikis it seems misplaced, but it maybe caused by some plugin I have installed.
![image](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/9b07d6d3-c82b-4e4f-b8ee-6e3c37af71b2)

**Comment by my17560** [comment]
Hi.
I don't know how to make the "Additional Plugins" header appear on the screen.
Is there an option to make it appear or do I need to install a plugin?

**Comment by eduardomozart** [comment]
You need to have plugins installed that add this section to the "Admin" page of DokuWiki, like BatchEdit, Move, SearchIndex etc.

**Comment by my17560** [comment]
Thank you!
I fixed and committed. Please try.

**Comment by eduardomozart** [comment]
Hello,
I can confirm that's working as expected now. Thank you!
