### ISSUE TITLE
Overlap of long links

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#72]
Hello,
I have posted the following link at my wiki: https://asp.arubanetworks.com/downloads;products=HPE%20Routers;productSeries=HPE%20%20VSR1000%20Virtual%20Services%20Router%20Series

But it seems to overlap page width:

![image](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/358e156b-3690-43c1-a8f8-9349a642ddb2)

**Comment by my17560** [comment]
Hi.

I updated and committed the modification. Could you "re-install" and try it?

**Comment by eduardomozart** [comment]
I can confirm that it's now working as expected. Thank you!
