### ISSUE TITLE
No padding when align image to the right or to the left

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#79]
The text seems near from images when align them to the left or to the right. The image below doesn't seem so bad, but 
maybe some padding could be set on ``.medialeft`` and ``.mediaright`` CSS classes so it would seem more natural.
<img width="696" alt="image" src="https://github.com/tillbiskup/dokuwiki-caption/assets/2974895/960fc54d-b992-4ae3-b623-9b6c7ce20c5f">

**Comment by my17560** [comment]
Hi, thank you for your report.

I've added margin to those aligned media, as same as the original DokuWiki template.
Please re-install to apply.

**Comment by eduardomozart** [comment]
Hello @my17560 
Thank you! I can confirm that now the padding is set. =)
<img width="696" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/f2a12d9a-fcfa-4b88-98c2-e12be4ca9224">
