### ISSUE TITLE
Sidebar doesn't work when defer_js is disabled 

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#8]
Hi,

it seems that when the feature flag "defer_js" is disabled, the sidebar toc/highlighting is not working.  Unfortunately not all plugins are compatible with "defer_js" yet.

Is there a way to have the sidebar working even with a disabled "defer_js"?

**Comment by my17560** [comment]
Problem confirmed. 

By disabling the "defer-js" option, the theme script starts executing before the sidebar is loaded.
I fixed it to execute when contents are loaded. Please Re-install the theme.

Thanks for your info. It really helped me fix this problem. It would take much longer to fix without it.

**Comment by fthommen** [comment]
You are awesome.  After I figured out, that the sidebar must _really only_ contain "strong" (** Title **) formatting and no headers (== Title ==) to work properly :-), the fixed version worked just fine with defer_js disabled.  Thx again (next question is coming already :-)
