### ISSUE TITLE
IndexMenu JS Treenew isn't being used to navigation

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#81]
IndexMenu now uses Fancytree and the legacy tree (https://github.com/my17560/dokuwiki-template-readthedokus/issues/78) will be deprecated into the future. I added a commit to the IndexMenu code that was already commited (https://github.com/samuelet/indexmenu/pull/292) that adds the "data-wiki-id" attr to IndexMenu Fancytree (Treenew), but it isn't enable navigation (Next/Prev buttons) on this template.
I believe it happens because now IndexMenu uses AJAX to load the sidebar and it isn't completed loaded when the page is loaded and the "Next/Prev" buttons are gathered by the template. Maybe if the template detects the presence of the ``.indexmenu_js2``  it could wait it fully load (``.fancytree-plain``) before attempt to gather the "Next/Prev" button, or we can discuss with IndexMenu devs if we could trigger custom events after Fancytree is fully loaded.

**Comment by my17560** [comment]
I don't think It is possible to use next/previous button with Treenew because it only retrieves child nodes when the node is opened.

![スクリーンショット 2024-02-03 15 15 07](https://github.com/my17560/dokuwiki-template-readthedokus/assets/49435291/7e74c25e-8403-4284-96e9-1875c77fa3c2)

When you are on "2. 3CX" namespace, the child node doesn't exist yet. It gets the child node when you open the namespace. So unless you don't open the namespace, this theme can't know if there is a child.

If you can expand all the menu items like this "{{indexmenu>..|js treenew nsort}}" it'll work.

**Comment by eduardomozart** [comment]
Hello,
I can confirm that it's working on child pages (when I access ":3cx" namespace it shows the "Next" and "Previous" buttons), but it didn't seem to work on Start page, but I'm not sure why.
<img width="1281" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/e8b9a7f9-ec47-455a-8429-0a8e4145c7e5">
Maybe the template could be updated to fetch namespace directly from DokuWiki PHP internal functions and build navigation through there (please remember to respect ACL)?

**Comment by my17560** [comment]
Sorry, I was wrong that expanding all the children at start could solve the problem.

As you said, since IndexMenu uses AJAX, I need to know when it finishes creating the index. I believe the problem could be solved if IndexMenu triggers a Javascript event when it finishes. Then this theme re-reads the index when the event is fired in the event-hander.

**Comment by eduardomozart** [comment]
I added the following code to ``conf/userscript.js`` and it seems I was able to hook an event to tree load itself, maybe the template could be updated to handle those events too:

```
  jQuery(".indexmenu_js2").each(function(){
        jQuery(this).fancytree({
            init: function(event, data){
                alert("test");
            }
        });
  });
```

**Comment by my17560** [comment]
Hi, thanks for your research. That helped me!
I've fixed the theme and updated it. Could you try?

Be noted, that it won't follow pages unless the folder is opened like I said before.

**Comment by eduardomozart** [comment]
I commited the PR #82 to add a missing comma that throws an error on JS.php.

**Comment by eduardomozart** [comment]
Hello @my17560,
I noticed that on your commit https://github.com/my17560/dokuwiki-template-readthedokus/commit/db34d7d4973ab1fcf758cdb75c701b53c236a616 you enabled the trigger of "fancytreexpand" event, but I'm not sure why.
Every time I expand an item it goes to the TOC, as can be seen below:
![GravacaodeTela2024-03-06as16 06 28-ezgif com-video-to-gif-converter](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/79b7e642-c4a8-46e7-a132-940e54ba2a05)

**Comment by eduardomozart** [comment]
There's also this odd behavior that I'm not sure if it's intended.
When the page has no child, it seems to be attached to the sidebar as expected:
<img width="1212" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/0eb4ee38-65b0-444c-88eb-90a38c693379">
But when it has child pages, the TOC isn't attached to the sidebar itself, instead it shows on the "TOC" section of the sidebar.
<img width="544" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/84b4bcaf-367d-4d92-a646-b6f315910414">

**Comment by my17560** [comment]
For the first issue, I'm sorry my last fix was sloppy. I refactored and fixed the script. Could you try it?
For the second issue, does the element have "data-wiki-id"? If not, the theme can't embed the TOC in place.

**Comment by eduardomozart** [comment]
Hello @my17560,
Thank you for your response. I can confirm that now the first issue seems to be fixed.
The later issue I'm not sure why the TOC is above, it has the "data-wiki-id" parameter on it, as can be seen below:
<img width="644" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/7d18fac5-3358-4870-bf41-e8aa1ed52fc9">
Here's my sidebar file content:
```
** Ferramentas do Wiki **

  * [[this>doku.php?id=start|Página principal]]
  * [[this>doku.php?id=wiki:plugin:addnewpage:newpage|Criar página]]

** Barra de Navegação **

{{indexmenu>..:#1|js#awesome navbar nsort nogroup treenew}}
```

**Comment by my17560** [comment]
Ok, I understand the situation. The reason the TOC is not embedded is that your current ID on URL "3cx:phone" is different from data-wiki-id "3cx:phone:" (notice the last colon).

I want to re-create the situation on my PC. What's the simplest directory structure that can confirm your situation? I'm not familiar with the indexmenu and I can't create it on my own.

like this?

pages/
    3cx/
        dashboard.txt
        users.txt
        voicechat.txt
    phones/
        (I want to know what's inside this directory)

**Comment by eduardomozart** [comment]
Here is it:
```
pages/
    sidebar.txt
    3cx/
        dashboard.txt
        users.txt
        voicechat.txt
        phones/
            add.txt
            add/
               templates.txt
```

**Comment by my17560** [comment]
I can't make "4. Phones" appear in the sidebar although I created the folders and files as you said. Am I missing something?

![スクリーンショット 2024-03-20 23 16 16](https://github.com/my17560/dokuwiki-template-readthedokus/assets/49435291/7a458369-71b1-4ebf-97d2-b4a95223a35e)

**Comment by my17560** [comment]
Thanks for you demo pages. I fixed the theme and committed. Could you try?

**Comment by eduardomozart** [comment]
Now it seems to be working as expected.
<img width="300" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/566e618f-aced-4122-867c-fcae4281b2d0">
Thank you!

**Comment by my17560** [comment]
Thank you for testing! I'll fix the CSS also.

**Comment by eduardomozart** [comment]
> Thank you for testing! I'll fix the CSS also.

I believe you're looking for https://github.com/my17560/dokuwiki-template-readthedokus/blob/e0aba490fa9aebaf602fb9cbbc5cbdf5494e6bd8/css/sidebar.css#L156, right? Maybe it should be 100% to fit the sidebar width.

**Comment by my17560** [comment]
On my computer, it looks like this.

![sidebar](https://github.com/my17560/dokuwiki-template-readthedokus/assets/49435291/9e727ff9-ae13-47a8-8acd-84eb641a6e94)

I want to move the TOC slightly to the left, make the TOC width 100%, and make scroll bars disappear.

**Comment by eduardomozart** [comment]
Oh, I see. This issue was caused by me. I wasn't able to reproduce it on my machine but I was able to reproduce it on my boss PC. This is the root cause:
https://github.com/my17560/dokuwiki-template-readthedokus/blob/e0aba490fa9aebaf602fb9cbbc5cbdf5494e6bd8/css/sidebar.css#L347
I want to troubleshoot this issue but I wasn't able to troubleshoot it yet, but removing that line, the following issue happens:
<img width="1441" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/3cad0ec4-4e97-409f-bed7-778e1af0eaef">

**Comment by my17560** [comment]
Hello, I updated the CSS. But be careful I bet it'll break your styles. I changed only sidebar.css, so please take a backup before updating.

**Comment by eduardomozart** [comment]
I created the PR to fix a regression on template in https://github.com/my17560/dokuwiki-template-readthedokus/pull/84.
Before the fix:
![image](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/af599a30-eaea-4cfe-81ce-7b37926c6777)
After the fix:
![image](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/3e778ce3-e17b-49ca-a986-050cd9aff916)

**Comment by eduardomozart** [comment]
I'm not sure if it's fixable, but I can't scroll to read full text as seen in:
![image](https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/11f7e797-d38c-40ea-9667-3a0fe0cfdf1b)
If it's not possible to fix it, I'll close this issue, no problem. Anyway, I'll create a PR on IndexMenu to add "title" attr to "a" tag as an workaround, so user can hover the text to read title if needed.

**Comment by eduardomozart** [comment]
There also seems another regression introduced by your fixes. It seems that the dropdown button for namespaces that contains child items isn't shown. I created the PR https://github.com/my17560/dokuwiki-template-readthedokus/pull/86 that fixes this issue.
Before the fix: 
<img width="276" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/b7ffa587-c643-411c-b24d-62926a4a9ec5">
After the fix:
<img width="276" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/afd8ab3f-afdf-4e83-b64d-b8bb36c70c3b">

**Comment by eduardomozart** [comment]
I noticed a strange issue when editing directly the "Plano de rede" section from the file below and clicking on [Preview] button. It seems that the ``.fancytreetitle`` class width breaks the IndexMenu TreeNew ns titles, but I was unable to reproduce it on other pages, it only happens on ``conceitos:rede`` page while editing any section and previewing them (not only "Plano de rede" section.
<img width="1441" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/9b3a5ccd-6928-4c63-80b9-9b3a5e92f62b">
The affect file content is in attachment:
[rede.txt](https://github.com/my17560/dokuwiki-template-readthedokus/files/15079475/rede.txt)
It seems that it only happens when this file is a child page of an existing namespace (e.g. ``:playground:rede``) and while editing and previewing a section (not the full page).

**Comment by my17560** [comment]
Hi, thank you for pull request. I merged them and committed the new style. Could you try?

As for the horizontal scroll, I don't have a plan to add scrollbars to the sidebar, but you can add the below style to show the scrollbar in userall.css.

```
#dokuwiki__aside #sidebar .indexmenu_js2 .li {
	overflow-x: auto;
}
```

**Comment by eduardomozart** [comment]
It seems great, no issues to report so far. Closing this issue.
