### ISSUE TITLE
Larger title with no spaces seems misaligned while Editing page

### ISSUE THREAD

**Issue by eduardomozart** [my17560/dokuwiki-template-readthedokus#87]
Hello,
When editing a page with a big title with no spaces on it, the title seems misaligned when clicking to preview draft while editing a page:
<img width="1160" alt="image" src="https://github.com/my17560/dokuwiki-template-readthedokus/assets/2974895/3ca7ab4b-5853-48fd-9539-5d74df122dbf">

**Comment by my17560** [comment]
This should be fixed by the last commit. Could you try?

**Comment by eduardomozart** [comment]
It seems fixed. Thank you!
