### ISSUE TITLE
Using with dokuprism or codeprism - unsightly borders around syntax

### ISSUE THREAD

**Issue by megatron-uk** [my17560/dokuwiki-template-readthedokus#94]
When I use the template along with either dokuprism or codeprism I get unsightly highlighting around all of the parsed syntax in a code block. 

Example:

![codeprism](https://github.com/user-attachments/assets/c83b280f-5c07-4992-9765-c39a819733fd)

This is just a simple `<code>blah blah</code>` section, nothing fancy.

When I use the standard dokuwiki template the white boxes around the parsed code syntax are not present.

I've tried various combinations of extra tags to dokuprism and codeprism, as well as css variants (dark, light, okaida, etc) and they all seem to have the same highlighting artifacts when readthedokus is the active template.

Any ideas where we can change that behaviour?

**Comment by megatron-uk** [comment]
So the offending styling is in: _readthedokus/css/basic.css_

**Remove** the following entry to have dokuprism or codeprism apply their correct styling:

```
code
{
        background-color: __background_monospace__;
        border: 1px solid __border_monospace__;
        color: __text_monospace__;
        font-family: SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, Courier, monospace;
        font-size: 75%;
        max-width: 100%;
        padding: 2px 5px;
        overflow-wrap: break-word;
}
```

A more elegant solution would be to have a configurable option for the template to not over-ride _code_ tags.

**Comment by my17560** [comment]
Thank you for your report.

I've confirmed the bug and confirmed removing the code style fixes this bug. It seems that the style is not necessary but I don't remember why I added the style.

I removed the style and committed the theme. Could you re-install the theme and try it?

**Comment by megatron-uk** [comment]
Yes, re-downloading and unpacking the latest version with the removed code css style does indeed resolve the issue.
